Gabriel_James/Controllers/OrderController.cs
using Gabriel_James.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Gabriel_James.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRepository repository;
        private Basket basket;
        public OrderController(IOrderRepository repoService, Basket basketService)
        {
            repository = repoService;
            basket = basketService;
        }
        public ViewResult Checkout() => View(new Order());
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (basket.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                order.Lines = basket.Items.ToArray();
                repository.SaveOrder(order);
                basket.Clear();
                return RedirectToPage("/Completed", new { orderId = order.OrderID });
            }
            else
            {
                return View();
            }
        }
    }
}

Gabriel_James/Pages/Completed.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Gabriel_James.Pages
{
    public class CompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Gabriel_James/Pages/Shop.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Gabriel_James.Infastructure;
using Gabriel_James.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Gabriel_James.Pages
{
    public class ShopModel : PageModel
    {
        private IBookstoreRepository repo { get; set; }
        public ShopModel (IBookstoreRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }
        public Basket basket { get; set; }
        public string ReturnUrl { get; set; }
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";

        }

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookId);
           

            basket.AddItem(b, 1);


            return RedirectToPage(new { ReturnUrl = returnUrl });


        }

        public IActionResult OnPostRemove(long bookId, string returnUrl)
        {
            basket.RemoveItem(basket.Items.First(x =>
                x.Book.BookId == bookId).Book);
            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

Gabriel_James/Pages/Completed.cshtml
@page
@model Gabriel_James.Pages.CompletedModel
@{
}
<div class="text-center">
    <h2>Thanks!</h2>
    <p>Thanks for placing order #@OrderId</p>
    <p>We'll ship your goods as soon as possible.</p>
    <a class="btn btn-primary" asp-controller="Home">Return to Store</a>
</div>
@functions {
    [BindProperty(SupportsGet = true)]
    public string OrderId { get; set; }
}

Gabriel_James/Pages/Shop.cshtml
@page
@model Gabriel_James.Pages.ShopModel
@{
}
@*Here I used the text lg center to center the header your cart*@
<h2 class="text-lg-center">Your Cart</h2>

<table class="table table-bordered table-striped d-xl-table">

    <thead>
        <tr>
            <th>Book</th>
            <th>Cost</th>
            <th>Quantity</th>
            <th>Subtotal</th>
        </tr>
    </thead>

    <tbody>
        @foreach(var i in Model.basket.Items)
            {
        <tr>
            <td>@i.Book.Title</td>
            <td>@i.Book.Price</td>
            <td>@i.Quantity</td>
            <td id="price">@(i.Quantity * i.Book.Price)</td>

            <td class="text-center">
                <form asp-page-handler="Remove" method="post">
                    <input type="hidden" name="BookId"
                           value="@i.Book.BookId" />
                    <input type="hidden" name="returnUrl"
                           value="@Model.ReturnUrl" />
                    <button type="submit" class="btn btn-sm btn-danger">
                        Remove
                    </button>
                </form>
            </td>
        </tr>
            }
    </tbody>

    <tfoot>
@*I used the alert info class for the total row on the table that I made*@
        <tr class="alert-info">
            <td colspan="3">Total:</td>
            <td>@Model.basket.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>


</table> 

<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Exit</a>
    <a class="btn btn-primary" asp-action="Checkout" asp-controller="Order">
        Checkout
    </a>
</div>

Gabriel_James/Pages/_ShopLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2">Book List</span>
    </div>

    <div class="n-1 p-1">
        @RenderBody()
    </div>
</body>
</html>